### ISSUE TITLE
'sudo apt update' fails with errors

### ISSUE THREAD

**Issue by star-buck** [blue-systems/neon-pinebook#84] opened 2018-06-03 12:35 UTC

**Comment by bhush9** [comment] 2018-06-04 04:15
Any specific errors? I can't seem to reproduce this.

**Comment by bhush9** [comment] 2018-06-20 07:29
Marking this as ready for QA as I am unable to reproduce this error on last two images: https://files.kde.org/neon/images/pinebook-remix-nonfree/bionic/20180620-0516/ is the latest I have tested.

**Comment by bhush9** [comment] 2018-07-30 13:36
This should be fixed in user edition based image: http://files.kde.mirror.pangea.pub/neon/images/pinebook-remix-nonfree/neon-pinebook-remix-useredition-20180730-1137-arm64.img.gz

**Closed as completed** 2018-08-07 13:44 UTC
Labels: bug, ready for QA, Next
