### ISSUE TITLE
kamoso: doesnt start

### ISSUE THREAD

**Issue by star-buck** [blue-systems/neon-pinebook#80] opened 2018-06-01 09:00 UTC

**Comment by bhush9** [comment] 2018-06-01 09:18
(Same issue as #81) Needs packaging.

**Comment by bhush9** [comment] 2018-06-01 15:10
Fixed in https://files.kde.org/neon/images/pinebook-remix-nonfree/bionic/20180601-1242/

**Comment by bhush9** [comment] 2018-06-20 07:29
Can't reproduce in : https://files.kde.org/neon/images/pinebook-remix-nonfree/bionic/20180620-0516/

**Comment by bhush9** [comment] 2018-07-30 13:37
It starts properly in : http://files.kde.mirror.pangea.pub/neon/images/pinebook-remix-nonfree/neon-pinebook-remix-useredition-20180730-1137-arm64.img.gz

**Closed as completed** 2018-08-06 13:21 UTC
Labels: bug, ready for QA, Next
