### ISSUE TITLE
discover: doesnt start

### ISSUE THREAD

**Issue by star-buck** [blue-systems/neon-pinebook#81] opened 2018-06-01 09:10 UTC

**Comment by bhush9** [comment] 2018-06-01 09:16
regression in kirigami, https://phabricator.kde.org/R858:b176593771c2049efb3b14dbf57f8ec706181312 already fixed, needs to be packaged.

**Comment by bhush9** [comment] 2018-06-01 10:49
Edit: the fix mentioned in commit doesn't actually work : CC: @aleixpol @notmart

**Comment by bhush9** [comment] 2018-06-01 15:10
Fixed in https://files.kde.org/neon/images/pinebook-remix-nonfree/bionic/20180601-1242/

**Comment by bhush9** [comment] 2018-06-20 07:29
Can't reproduce this in : https://files.kde.org/neon/images/pinebook-remix-nonfree/bionic/20180620-0516/

**Comment by bhush9** [comment] 2018-07-30 13:37
It starts in the http://files.kde.mirror.pangea.pub/neon/images/pinebook-remix-nonfree/neon-pinebook-remix-useredition-20180730-1137-arm64.img.gz

**Closed as completed** 2018-08-06 13:21 UTC
Labels: bug, ready for QA, Next
